<a href="https://colab.research.google.com/github/LadonV/Operation-Research/blob/main/Project_Assignments/LPAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Programming Assignment

## Redo a WeBWorK Question Using Python

Consider WW Set 03 Problem 3.  Using python, do the following:
1. Copy your problem here.
1. Find corner points.  
2. Graph feasible set.
3. Find the corner that maximizes the objective function $P = 3x+2y$.
4. Introduce slack variables, find the corner points again.
5. Solve using a built-in Linear Programming Solver.  Compare your answers.

## Redo a WeBWorK Question Using Python

Consider WW Set 04 Problem 6.  Using python, do the following:
1. Write the equations that describe the problem completely using $\LaTeX$ encoding.   
1. Find corner points.  
2. Graph feasible set.
3. Find the corner that maximizes the objective function.
4. Introduce slack variables, find the corner points again.
5. Solve using a built-in Linear Programming Solver.  Compare your answers.

# Task
Solve the given linear programming problem: maximize $P=5x_1+6x_2+2x_3$ subject to $-x_1+x_2+10x_3 \le 5$, $-x_1+2x_2+7x_3 \le 4$, $x_1 +8x_2 +9x_3 \le 7$, $x_1 \ge 0$, $x_2 \ge 0$, $x_3 \ge 0$. Find the optimal values of $x_1$, $x_2$, and $x_3$, and the maximum value of $P$.

## Define the problem

### Subtask:
Write out the objective function and constraints in a clear format.


**Reasoning**:
Express the objective function and constraints in a clear format as requested in the instructions.



In [1]:
print("Objective Function to Maximize:")
print("P = 5x1 + 6x2 + 2x3")
print("\nSubject to the Constraints:")
print("-x1 + x2 + 10x3 <= 5")
print("-x1 + 2x2 + 7x3 <= 4")
print("x1 + 8x2 + 9x3 <= 7")
print("\nNon-negativity Constraints:")
print("x1 >= 0")
print("x2 >= 0")
print("x3 >= 0")

Objective Function to Maximize:
P = 5x1 + 6x2 + 2x3

Subject to the Constraints:
-x1 + x2 + 10x3 <= 5
-x1 + 2x2 + 7x3 <= 4
x1 + 8x2 + 9x3 <= 7

Non-negativity Constraints:
x1 >= 0
x2 >= 0
x3 >= 0


## Solve using a built-in linear programming solver

### Subtask:
Use a Python library like SciPy to solve the linear programming problem.


**Reasoning**:
Import the necessary function from scipy and define the parameters for the linear programming problem, then solve it and print the results.



In [2]:
from scipy.optimize import linprog
import numpy as np

c = np.array([-5, -6, -2])

A_ub = np.array([
    [-1, 1, 10],
    [-1, 2, 7],
    [1, 8, 9]
])

b_ub = np.array([5, 4, 7])

x1_bounds = (0, None)
x2_bounds = (0, None)
x3_bounds = (0, None)

result = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=[x1_bounds, x2_bounds, x3_bounds])

print(result)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -35.0
              x: [ 7.000e+00  0.000e+00  0.000e+00]
            nit: 0
          lower:  residual: [ 7.000e+00  0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  3.400e+01  4.300e+01]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 1.200e+01  1.100e+01  0.000e+00]
                 marginals: [-0.000e+00 -0.000e+00 -5.000e+00]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0


## Introduce slack variables

### Subtask:
Rewrite the constraints as equalities by introducing slack variables.


**Reasoning**:
Introduce slack variables to convert the inequality constraints into equalities.



In [3]:
print("Original Constraints:")
print("-x1 + x2 + 10x3 <= 5")
print("-x1 + 2x2 + 7x3 <= 4")
print("x1 + 8x2 + 9x3 <= 7")
print("\nConstraints with Slack Variables:")
print("-x1 + x2 + 10x3 + s1 = 5")
print("-x1 + 2x2 + 7x3 + s2 = 4")
print("x1 + 8x2 + 9x3 + s3 = 7")
print("\nwhere s1, s2, and s3 are non-negative slack variables (s1 >= 0, s2 >= 0, s3 >= 0).")

Original Constraints:
-x1 + x2 + 10x3 <= 5
-x1 + 2x2 + 7x3 <= 4
x1 + 8x2 + 9x3 <= 7

Constraints with Slack Variables:
-x1 + x2 + 10x3 + s1 = 5
-x1 + 2x2 + 7x3 + s2 = 4
x1 + 8x2 + 9x3 + s3 = 7

where s1, s2, and s3 are non-negative slack variables (s1 >= 0, s2 >= 0, s3 >= 0).


## Find corner points using slack variables

### Subtask:
Determine the corner points of the feasible region using the equations with slack variables.


**Reasoning**:
Define the system of linear equations with slack variables and identify all possible combinations of setting 3 variables to zero to find potential corner points by solving the resulting systems.



In [4]:
import numpy as np
from itertools import combinations

A = np.array([
    [-1, 1, 10, 1, 0, 0],
    [-1, 2, 7, 0, 1, 0],
    [1, 8, 9, 0, 0, 1]
])
b = np.array([5, 4, 7])

n_vars = A.shape[1]
n_constraints = A.shape[0]
n_zero_vars = n_vars - n_constraints

corner_points = []

for zero_indices in combinations(range(n_vars), n_zero_vars):
    solve_indices = [i for i in range(n_vars) if i not in zero_indices]

    A_sub = A[:, solve_indices]

    if np.linalg.det(A_sub) != 0:
        solution_sub = np.linalg.solve(A_sub, b)

        solution = np.zeros(n_vars)
        for i, original_index in enumerate(solve_indices):
            solution[original_index] = solution_sub[i]

        if np.all(solution >= -1e-9):
            corner_points.append(solution)

print("Potential Corner Points (x1, x2, x3, s1, s2, s3):")
for point in corner_points:
    print(point)

Potential Corner Points (x1, x2, x3, s1, s2, s3):
[0. 0. 0. 5. 4. 7.]
[0.  0.  0.5 0.  0.5 2.5]
[0.    0.875 0.    4.125 2.25  0.   ]
[0.         0.35211268 0.46478873 0.         0.04225352 0.        ]
[ 7.  0.  0. 12. 11.  0.]
[1.31578947 0.         0.63157895 0.         0.89473684 0.        ]


**Reasoning**:
Filter the potential corner points to keep only the non-negative solutions which represent the feasible corner points of the original variables.



In [5]:
feasible_corner_points = [point for point in corner_points if point[0] >= -1e-9 and point[1] >= -1e-9 and point[2] >= -1e-9]

print("\nFeasible Corner Points (x1, x2, x3):")
for point in feasible_corner_points:
    print(point[:3])


Feasible Corner Points (x1, x2, x3):
[0. 0. 0.]
[0.  0.  0.5]
[0.    0.875 0.   ]
[0.         0.35211268 0.46478873]
[7. 0. 0.]
[1.31578947 0.         0.63157895]


## Find the corner that maximizes the objective function

### Subtask:
Find the corner that maximizes the objective function.


**Reasoning**:
Define the objective function and iterate through the feasible corner points to find the one that maximizes the objective function.



In [6]:
def objective_function(point):

    return 5 * point[0] + 6 * point[1] + 2 * point[2]

max_p = -float('inf')
optimal_corner_point = None

for point in feasible_corner_points:
    p_value = objective_function(point[:3])
    if p_value > max_p:
        max_p = p_value
        optimal_corner_point = point[:3]

print("\nOptimal Corner Point (x1, x2, x3):")
print(optimal_corner_point)
print(f"\nMaximum value of P: {max_p}")


Optimal Corner Point (x1, x2, x3):
[7. 0. 0.]

Maximum value of P: 35.0
